/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/meforweb.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/meforweb.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.28, 0.613, 0.025]} scale={0.001}>
        <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[-36.2, -10.626, -243.72]} scale={1.343} />
      </group>
      <group position={[0.21, 0.613, 0.353]} scale={0.001}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Material} position={[69.601, -135.649, -533.97]} scale={1.143} />
      </group>
      <mesh geometry={nodes.Mesh_0.geometry} material={materials.Material_0} scale={1.911} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[0, 0.32, -0.268]} rotation={[Math.PI / 2, 0, 0]} scale={0.424} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Material} position={[-0.353, 0.284, 0]} rotation={[0.345, -0.184, 0.047]} scale={0.041} />
      <mesh geometry={nodes.BezierCurve.geometry} material={materials.Material} position={[0.368, 0.276, 0]} scale={0.305} />
      <mesh geometry={nodes.Cone.geometry} material={materials.Material} position={[-0.249, 0.152, -0.137]} rotation={[0.941, -0.776, 0.316]} scale={-0.046} />
    </group>
  )
}

useGLTF.preload('/meforweb.glb')
